# Generated by Django 2.0 on 2018-01-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing_description', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('price', models.FloatField(verbose_name='price')),
                ('found_price', models.FloatField(verbose_name='found_price')),
            ],
        ),
    ]
