# Generated by Django 2.0 on 2018-01-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180103_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='flag',
            field=models.IntegerField(default=3, verbose_name='flag'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(choices=[(1, 'Jan'), (2, 'Sam'), (3, 'Radim'), (4, 'Stepan')], default=1, max_length=6),
        ),
        migrations.AlterField(
            model_name='thing',
            name='found_price',
            field=models.FloatField(null=True, verbose_name='found_price'),
        ),
    ]
