# Generated by Django 2.0 on 2018-01-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180103_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.IntegerField(choices=[(1, 'Jan'), (2, 'Sam'), (3, 'Radim'), (4, 'Stepan')], default=1),
        ),
    ]
