# Generated by Django 2.0 on 2018-01-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180104_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='net_spendings',
            field=models.FloatField(default=0, verbose_name='spendings'),
        ),
    ]
