# Generated by Django 2.0 on 2018-01-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_person_net_spendings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='net_spendings',
            field=models.FloatField(default=0, verbose_name='net_spendings'),
        ),
    ]
